openapi: 3.1.0
info:
  title: Accounts
  version: '1.0'
  summary: The API for accessing InteraApps Accounts
servers:
  - url: 'http://accounts.interaapps.de/api/v2'
    description: API
paths:
  /user:
    get:
      summary: getUser
      operationId: get-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
components:
  schemas:
    Account:
      title: Account
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-internal: false
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses: {}
