openapi: 3.1.0
info:
  title: Accounts
  version: '1.0'
  summary: The API for accessing InteraApps Accounts
servers:
  - url: 'http://accounts.interaapps.de/api/v2'
    description: API
paths:
  /user:
    get:
      summary: getUser
      operationId: get-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
components:
  schemas:
    Account:
      title: Account
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      x-internal: false
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        description:
          type: string
          description: The description
        mail:
          type: string
          format: email
        full_name:
          type: string
        birthday:
          type: string
          format: date
          example: '1997-10-31'
          description: Date
        favorite_color:
          type: string
          description: Favourite color (7 Chars long)
          format: color
          minLength: 0
          maxLength: 7
          example: '#00FF00'
        profile_picture:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses: {}
